services:
  - type: web
    name: seu-app-laravel
    runtime: php
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      php artisan config:cache
      php artisan view:cache
      php artisan route:cache
      php artisan storage:link
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr