services:
  - type: web
    name: vinivinil
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan view:cache
      php artisan route:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 8080
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          name: vinivinil-db
          type: postgres
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromService:
          name: vinivinil-db
          type: postgres
          property: database
      - key: DB_USERNAME
        fromService:
          name: vinivinil-db
          type: postgres
          property: user
      - key: DB_PASSWORD
        fromService:
          name: vinivinil-db
          type: postgres
          property: password
    ports:
      - 8080

databases:
  - name: vinivinil-db
    databaseName: vinivinil
    user: vinivinil
